version: '3.8'
services:
  db:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=postgres12
      - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "entrypoint.sh && bash init.sh"
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle:delegated
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    restart: on-failure
    volumes:
      - .:/myapp
    command: bash -C "start_sidekiq.sh"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6380:6379'
    volumes:
      - ./volumes/redis-data:/data
volumes:
  bundle:
  redis:
  db_data: