default: &default
    port: '6379'

development:
    <<: *default
    db: 0 
    host: <%= ENV['REDIS_HOST'] || 'localhost' %>

test:
    <<: *default
    db: 2
    host: <%= ENV['REDIS_HOST'] || 'localhost' %>